# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/server" # Changed to .exe
  bin = "tmp/main.exe" # Changed to .exe
  full_bin = ""
  args = []
  env = []
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor", "docs", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[run]
  cmd = "./tmp/main.exe" # Changed to .exe
  args = []
  env = []
  delay = 500 # ms
  app_start_check = "tcp" # or "log"
  app_start_check_delay = "1s"
  app_start_check_timeout = "10s"
  app_start_check_log_regex = ""

[misc]
  clean_on_exit = true